import { meetingRequestSchema } from "@/schema/validationSchemas.js";
import { Room } from "../types/interfaces.js";
import { z } from "zod";

// Utility function to transform server room data to include resources array
export const transformRoomData = (serverRoom: any): Room => {
  const resources: string[] = [];
  
  if (serverRoom.displayProjector) {
    resources.push("Projector");
  }
  if (serverRoom.displayWhiteboard) {
    resources.push("Whiteboard");
  }
  if (serverRoom.videoConferenceAvailable) {
    resources.push("Video Conference");
  }
  if (serverRoom.cateringAvailable) {
    resources.push("Catering");
  }

  return {
    ...serverRoom,
    resources,
    // Use a default image if none provided
    image: serverRoom.image || "https://images.unsplash.com/photo-1497366216548-37526070297c?w=500&h=300&fit=crop"
  };
};

export const mockRooms: Room[] = [
  {
    id: "1",
    name: "Conference Room A",
    capacity: 12,
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=500&h=300&fit=crop",
    displayProjector: true,
    displayWhiteboard: true,
    cateringAvailable: false,
    videoConferenceAvailable: true,
    createdAt: "2025-07-10T19:17:53.090Z",
    updatedAt: "2025-07-10T19:17:53.090Z",
    organizationId: "org-1",
    Organization: {
      id: "org-1",
      name: "Default Organization"
    },
    resources: ["Projector", "Whiteboard", "Video Conference"]
  },
  {
    id: "2",
    name: "Executive Boardroom",
    capacity: 8,
    image: "https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=500&h=300&fit=crop",
    displayProjector: false,
    displayWhiteboard: false,
    cateringAvailable: false,
    videoConferenceAvailable: true,
    createdAt: "2025-07-10T19:17:53.090Z",
    updatedAt: "2025-07-10T19:17:53.090Z",
    organizationId: "org-1",
    Organization: {
      id: "org-1",
      name: "Default Organization"
    },
    resources: ["Video Conference"]
  },
  {
    id: "3",
    name: "Creative Studio",
    capacity: 6,
    image: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=500&h=300&fit=crop",
    displayProjector: true,
    displayWhiteboard: true,
    cateringAvailable: false,
    videoConferenceAvailable: false,
    createdAt: "2025-07-10T19:17:53.090Z",
    updatedAt: "2025-07-10T19:17:53.090Z",
    organizationId: "org-1",
    Organization: {
      id: "org-1",
      name: "Default Organization"
    },
    resources: ["Whiteboard", "Projector"]
  },
  {
    id: "4",
    name: "Small Meeting Room",
    capacity: 4,
    image: "https://images.unsplash.com/photo-1556761175-b413da4baf72?w=500&h=300&fit=crop",
    displayProjector: false,
    displayWhiteboard: false,
    cateringAvailable: false,
    videoConferenceAvailable: false,
    createdAt: "2025-07-10T19:17:53.090Z",
    updatedAt: "2025-07-10T19:17:53.090Z",
    organizationId: "org-1",
    Organization: {
      id: "org-1",
      name: "Default Organization"
    },
    resources: []
  }
];

export const pastBookings: z.infer<typeof meetingRequestSchema>[] = [
  {
    id: 1,
    meetingTitle: "Meeting with John",
    name: "Alice Johnson",
    department: "Engineering",
    teamAgenda: "Discuss project progress",
    startTime: "10:00",
    endTime: "11:00",
    numberOfAttendees: 5,
    meetingType: "internal",
    requirements: ["Projector"],
    roomId: "1",
    status: "completed",
  },
  {
    id: 2,
    meetingTitle: "Project Review",
    name: "Bob Smith",
    department: "Product",
    teamAgenda: "Review quarterly milestones and future planning",
    startTime: "14:00",
    endTime: "15:30",
    numberOfAttendees: 8,
    meetingType: "external",
    requirements: ["Video Conference"],
    roomId: "2",
    status: "completed",
  },
  {
    id: 3,
    meetingTitle: "Design Sync",
    name: "Carol Lee",
    department: "Design",
    teamAgenda: "Sync on new branding assets",
    startTime: "09:00",
    endTime: "10:00",
    numberOfAttendees: 4,
    meetingType: "internal",
    requirements: ["Whiteboard"],
    roomId: "3",
    status: "completed",
  },
  {
    id: 4,
    meetingTitle: "Client Demo",
    name: "David Kim",
    department: "Sales",
    teamAgenda: "Demo new features to client",
    startTime: "16:00",
    endTime: "17:00",
    numberOfAttendees: 6,
    meetingType: "external",
    requirements: ["Projector", "Video Conference"],
    roomId: "1",
    status: "cancelled",
  },
  // Additional past bookings for better testing data
  {
    id: 21,
    meetingTitle: "Performance Review Session",
    name: "Tom Anderson",
    department: "HR",
    teamAgenda: "Quarterly performance evaluations and feedback",
    startTime: "09:00",
    endTime: "11:00",
    numberOfAttendees: 3,
    meetingType: "internal",
    requirements: ["Whiteboard"],
    roomId: "4",
    status: "completed",
  },
  {
    id: 22,
    meetingTitle: "API Integration Workshop",
    name: "Sophie Laurent",
    department: "Engineering",
    teamAgenda: "Technical deep-dive on third-party API integrations",
    startTime: "13:00",
    endTime: "15:00",
    numberOfAttendees: 7,
    meetingType: "internal",
    requirements: ["Projector", "Whiteboard"],
    roomId: "1",
    status: "completed",
  },
  {
    id: 23,
    meetingTitle: "Customer Onboarding Call",
    name: "Mark Stevens",
    department: "Customer Success",
    teamAgenda: "Help new enterprise client with platform setup",
    startTime: "11:00",
    endTime: "12:30",
    numberOfAttendees: 5,
    meetingType: "external",
    requirements: ["Video Conference"],
    roomId: "2",
    status: "completed",
  },
  {
    id: 24,
    meetingTitle: "Budget Planning Meeting",
    name: "Jennifer Walsh",
    department: "Finance",
    teamAgenda: "Allocate Q1 budget across departments",
    startTime: "14:00",
    endTime: "16:00",
    numberOfAttendees: 6,
    meetingType: "internal",
    requirements: ["Projector"],
    roomId: "3",
    status: "completed",
  },
  {
    id: 25,
    meetingTitle: "Technical Debt Review",
    name: "Carlos Mendez",
    department: "Engineering",
    teamAgenda: "Prioritize technical debt items for next quarter",
    startTime: "10:00",
    endTime: "11:30",
    numberOfAttendees: 8,
    meetingType: "internal",
    requirements: ["Whiteboard", "Projector"],
    roomId: "1",
    status: "completed",
  },
  {
    id: 26,
    meetingTitle: "Sales Strategy Session",
    name: "Nicole Brown",
    department: "Sales",
    teamAgenda: "Develop go-to-market strategy for new product line",
    startTime: "15:00",
    endTime: "17:00",
    numberOfAttendees: 9,
    meetingType: "internal",
    requirements: ["Whiteboard"],
    roomId: "2",
    status: "completed",
  },
  {
    id: 27,
    meetingTitle: "Compliance Training",
    name: "Robert Chen",
    department: "Legal",
    teamAgenda: "Mandatory training on new data privacy regulations",
    startTime: "09:30",
    endTime: "11:00",
    numberOfAttendees: 12,
    meetingType: "internal",
    requirements: ["Projector"],
    roomId: "1",
    status: "completed",
  },
  {
    id: 28,
    meetingTitle: "Product Roadmap Presentation",
    name: "Amanda Foster",
    department: "Product",
    teamAgenda: "Present product roadmap to stakeholders",
    startTime: "14:30",
    endTime: "16:00",
    numberOfAttendees: 10,
    meetingType: "internal",
    requirements: ["Projector", "TV Screen"],
    roomId: "2",
    status: "completed",
  },
  {
    id: 29,
    meetingTitle: "Emergency Incident Response",
    name: "Tyler Jackson",
    department: "DevOps",
    teamAgenda: "Post-mortem analysis of production outage",
    startTime: "08:00",
    endTime: "09:30",
    numberOfAttendees: 6,
    meetingType: "internal",
    requirements: ["Whiteboard"],
    roomId: "3",
    status: "completed",
  },
  {
    id: 30,
    meetingTitle: "Cancelled Team Building",
    name: "Laura Martinez",
    department: "HR",
    teamAgenda: "Team building activities and workshop",
    startTime: "13:00",
    endTime: "15:00",
    numberOfAttendees: 15,
    meetingType: "internal",
    requirements: ["TV Screen"],
    roomId: "1",
    status: "cancelled",
  },
];

export const upcomingBookings: z.infer<typeof meetingRequestSchema>[] = [
  {
    id: 5,
    meetingTitle: "Team Standup",
    name: "Clara Green",
    department: "Development",
    teamAgenda: "Daily team updates and blockers discussion",
    startTime: "09:00",
    endTime: "09:30",
    numberOfAttendees: 10,
    meetingType: "internal",
    requirements: ["Projector", "Whiteboard"],
    roomId: "1",
    status: "pending",
  },
  {
    id: 6,
    meetingTitle: "Client Presentation",
    name: "Daniel Kim",
    department: "Sales",
    teamAgenda: "Present new feature roadmap to the client",
    startTime: "14:00",
    endTime: "16:00",
    numberOfAttendees: 6,
    meetingType: "external",
    requirements: ["TV Screen"],
    roomId: "2",
    status: "pending",
  },
  {
    id: 7,
    meetingTitle: "Design Review",
    name: "Eva Brown",
    department: "Design",
    teamAgenda: "Finalize UI/UX elements for launch",
    startTime: "11:00",
    endTime: "12:00",
    numberOfAttendees: 4,
    meetingType: "internal",
    requirements: ["Whiteboard"],
    roomId: "3",
    status: "approved",
  },
  {
    id: 8,
    meetingTitle: "Board Meeting",
    name: "Frank Lee",
    department: "Executive",
    teamAgenda: "Quarterly performance review and planning",
    startTime: "10:00",
    endTime: "12:00",
    numberOfAttendees: 12,
    meetingType: "internal",
    requirements: ["Projector", "Video Conference"],
    roomId: "1",
    status: "pending",
  },
  {
    id: 9,
    meetingTitle: "Onboarding Session",
    name: "Grace Miller",
    department: "HR",
    teamAgenda: "Welcome new team members and introduce policies",
    startTime: "11:00",
    endTime: "12:00",
    numberOfAttendees: 3,
    meetingType: "internal",
    requirements: ["Whiteboard"],
    roomId: "3",
    status: "pending",
  },
  // Additional diverse booking requests for testing
  {
    id: 10,
    meetingTitle: "Emergency Bug Fix Meeting",
    name: "Alex Torres",
    department: "Engineering",
    teamAgenda: "Critical production issue needs immediate attention",
    startTime: "08:00",
    endTime: "09:00",
    numberOfAttendees: 8,
    meetingType: "internal",
    requirements: ["Projector", "Whiteboard"],
    roomId: "1",
    status: "pending",
  },
  {
    id: 11,
    meetingTitle: "Investor Pitch Rehearsal",
    name: "Sarah Chen",
    department: "Executive",
    teamAgenda: "Practice presentation for Series B funding round",
    startTime: "15:00",
    endTime: "17:00",
    numberOfAttendees: 5,
    meetingType: "internal",
    requirements: ["Projector", "TV Screen", "Video Conference"],
    roomId: "2",
    status: "approved",
  },
  {
    id: 12,
    meetingTitle: "Customer Discovery Call",
    name: "Mike Johnson",
    department: "Product",
    teamAgenda: "Interview customers about new feature requirements",
    startTime: "13:00",
    endTime: "14:30",
    numberOfAttendees: 4,
    meetingType: "external",
    requirements: ["Video Conference"],
    roomId: "4",
    status: "pending",
  },
  {
    id: 13,
    meetingTitle: "Security Audit Review",
    name: "Lisa Wang",
    department: "Security",
    teamAgenda: "Review quarterly security assessment findings",
    startTime: "16:00",
    endTime: "18:00",
    numberOfAttendees: 6,
    meetingType: "internal",
    requirements: ["Projector", "Whiteboard"],
    roomId: "3",
    status: "pending",
  },
  {
    id: 14,
    meetingTitle: "Partnership Negotiation",
    name: "James Rodriguez",
    department: "Business Development",
    teamAgenda: "Finalize terms with strategic partner",
    startTime: "10:30",
    endTime: "12:30",
    numberOfAttendees: 8,
    meetingType: "external",
    requirements: ["TV Screen", "Video Conference"],
    roomId: "2",
    status: "approved",
  },

];

// Mock data for available rooms - replace with API call later
export const mockAvailableRooms: Room[] = [
  {
    id: "1",
    name: "Conference Room A",
    time: "10:00 - 11:00 AM",
    capacity: 12,
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=200&h=200&fit=crop",
    status: "available",
    displayProjector: true,
    displayWhiteboard: true,
    cateringAvailable: false,
    videoConferenceAvailable: true,
    createdAt: "2025-07-10T19:17:53.090Z",
    updatedAt: "2025-07-10T19:17:53.090Z",
    organizationId: "org-1",
    Organization: {
      id: "org-1",
      name: "Default Organization"
    },
    resources: ["Projector", "Whiteboard", "Video Conference"],
  },
  {
    id: "2",
    name: "Executive Boardroom",
    time: "2:00 - 3:30 PM",
    capacity: 8,
    image: "https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=200&h=200&fit=crop",
    status: "available",
    displayProjector: false,
    displayWhiteboard: false,
    cateringAvailable: false,
    videoConferenceAvailable: true,
    createdAt: "2025-07-10T19:17:53.090Z",
    updatedAt: "2025-07-10T19:17:53.090Z",
    organizationId: "org-1",
    Organization: {
      id: "org-1",
      name: "Default Organization"
    },
    resources: ["Video Conference"],
  },
  {
    id: "3",
    name: "Creative Studio",
    time: "4:00 - 5:00 PM",
    capacity: 6,
    image: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=200&h=200&fit=crop",
    status: "available",
    displayProjector: true,
    displayWhiteboard: true,
    cateringAvailable: false,
    videoConferenceAvailable: false,
    createdAt: "2025-07-10T19:17:53.090Z",
    updatedAt: "2025-07-10T19:17:53.090Z",
    organizationId: "org-1",
    Organization: {
      id: "org-1",
      name: "Default Organization"
    },
    resources: ["Whiteboard", "Projector"],
  },
];